library(package = shinymanager)
library(package = shiny)
library(package = dplyr)
library(package = dbplyr)
library(package = data.table)
library(package = tidyr)
library(package = lubridate)
library(package = shiny)
library(package = shinydashboard)
library(package = shinyWidgets)
library(package = shinycssloaders)
library(package = ggthemes)
library(package = RColorBrewer)
library(package = scales)
library(package = DT)
library(package = readxl)
library(package = glue)
library(package = tidyverse)
library(package = MASS)
library(package = triangle)
library(package = waiter)
library(package = shinyjs) 
library(package = openxlsx)
library(package = prettydoc)
library(package = shinythemes)

#Carregando Alguns Objetos Globais
F_Motor_Quant_Riscos <- readRDS(file = "C:/Users/wesleysilva/Desktop/Funções/F_Motor_Quant_Riscos.rds")
EV_Total <- readRDS(file = "C:/Users/wesleysilva/Desktop/Funções/EV_Total.rds")
Paragrafo_HTML <- readRDS(file = "C:/Users/wesleysilva/Desktop/Funções/Paragrafo_HTML.rds")

load(file = "C:/Users/wesleysilva/Desktop/Projetos_Github/Agro_Front/Teste.RData")
Corte_Escolhido <- 3
Densidade <- density(x = subset(x = Tabela, Corte == Corte_Escolhido)$PR_SIM)
Dados <- data.frame(Valor = Densidade$x, Dens = Densidade$y)

home <- readRDS(file = "C:/Users/wesleysilva/Desktop/Projetos_Github/Agro_Front/tabs/ui/home.rds")
Ferramenta <- readRDS(file = "C:/Users/wesleysilva/Desktop/Projetos_Github/Agro_Front/tabs/ui/Ferramenta.rds")
Apoio <- readRDS(file = "C:/Users/wesleysilva/Desktop/Projetos_Github/Agro_Front/tabs/ui/Apoio.rds")

Template <- read_xlsx(path = "C:/Users/wesleysilva/Desktop/Projetos_Github/Agro_Front/Template.xlsx")
Template_2 <- read_xlsx(path = "C:/Users/wesleysilva/Desktop/Projetos_Github/Agro_Front/Template.xlsx", sheet = 2)
Lista <- list("Registro" = Template, "Sumario" = Template_2)
Exemplo <- read_xlsx(path = "C:/Users/wesleysilva/Desktop/Projetos_Github/Agro_Front/Exemplo.xlsx")

Credenciais <- data.frame("user" = c("marcio"), "password" = c("teste2460"), stringsAsFactors = FALSE)