library(package = shiny)
library(package = dplyr)
library(package = dbplyr)
library(package = data.table)
library(package = tidyr)
library(package = lubridate)
library(package = shiny)
library(package = shinydashboard)
library(package = shinyWidgets)
library(package = shinycssloaders)
library(package = ggthemes)
library(package = RColorBrewer)
library(package = scales)
library(package = DT)
library(package = readxl)
library(package = glue)
library(package = tidyverse)
library(package = MASS)
library(package = triangle)
library(package = waiter)
library(package = shinyjs) 
library(package = openxlsx)
library(package = prettydoc)

#Carregando Alguns Objetos Globais
F_Motor_Quant_Riscos <- readRDS(file = "C:/Users/wesleysilva/Desktop/Funções/F_Motor_Quant_Riscos")
EV_Total <- readRDS(file = "C:/Users/wesleysilva/Desktop/Funções/EV_Total")
Funcao_H1 <- readRDS(file = "C:/Users/wesleysilva/Desktop/Funções/Funcao_H1.rds")
Paragrafo_HTML <- readRDS(file = "C:/Users/wesleysilva/Desktop/Funções/Paragrafo_HTML.rds")

home <- readRDS(file = "C:/Users/wesleysilva/Desktop/Identificação/tabs/ui/home.rds")
Identificacao <- readRDS(file = "C:/Users/wesleysilva/Desktop/Identificação/tabs/ui/Identificacao.rds")
Apoio <- readRDS(file = "C:/Users/wesleysilva/Desktop/Identificação/tabs/ui/Apoio.rds")

Template <- read_xlsx(path = "C:/Users/wesleysilva/Desktop/Identificação/Template.xlsx")
Template_2 <- read_xlsx(path = "C:/Users/wesleysilva/Desktop/Identificação/Template.xlsx", sheet = 2)
Lista <- list("Registro" = Template, "Sumario" = Template_2)
Exemplo <- read_xlsx(path = "C:/Users/wesleysilva/Desktop/Identificação/Exemplo.xlsx")
